// GENERATED by scripts/build-execupack-data.mjs from the Hugging Face API
// (huggingface.co/experimentalmachines, every *-ExecuTorch repo). Do not edit by hand; re-run the script.
// One entry per published repo; builds group its .pte files by backend folder,
// chip and recipe, with the context windows (tokens) present.

export type PublishedBuild = {
  backend: "xnnpack" | "vulkan" | "qnn" | "mtk";
  chip: string | null;
  recipe: string;
  windows: number[];
};

export type PublishedRepo = {
  id: string;
  name: string;
  family: string;
  source: string | null;
  sha: string;
  lastModified: string;
  builds: PublishedBuild[];
};

export const publishedAsOf = "2026-10-04";

export const publishedRepos: PublishedRepo[] = [
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-1.2B-Instruct",
    "sha": "8184ae83cf4da8d5d337baa31197c6b85535dc3e",
    "lastModified": "2026-09-24",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic",
    "sha": "2c60db6066e0bdcd161885935aaf9c4f19e291e4",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-ExecuTorch",
    "name": "LFM2.5-2.6B",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-2.6B",
    "sha": "c19ce17cd4812c3b6912ce03ab2a19701541eb2d",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W4",
        "windows": [
          512
        ]
      },
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-heretic-ExecuTorch",
    "name": "LFM2.5-2.6B-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-2.6B-heretic",
    "sha": "7635b652d48c4594f440c9cea26cddb3d701920d",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-1B-Instruct-ExecuTorch",
    "name": "Llama-3.2-1B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-1B-Instruct",
    "sha": "0b5d9cf6ae23d83d754e34c219bd97dcafc834cf",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-3B-Instruct-ExecuTorch",
    "name": "Llama-3.2-3B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-3B-Instruct",
    "sha": "139939124e698cb8d9259c8347eaf6e0f2c0a7a0",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-0.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-0.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-0.5B-Instruct",
    "sha": "cff4d0471726bcb582f0d013a74ba36f26d86ff6",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-1.5B-Instruct",
    "sha": "0a912670f4bf6039d0192cc420960039bff0d402",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-3B-Instruct-ExecuTorch",
    "name": "Qwen2.5-3B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-3B-Instruct",
    "sha": "02ce1e421aaa50e64f895b77ec8ee6e6d678a515",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-Math-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-Math-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-Math-1.5B-Instruct",
    "sha": "aa5e6b9e4b4a41767dfbaeaac1dcd98b29560620",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-0.6B-ExecuTorch",
    "name": "Qwen3-0.6B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-0.6B",
    "sha": "c951161055a85f1edc32a31bb3ee44a6a2d8d440",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-1.7B-ExecuTorch",
    "name": "Qwen3-1.7B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-1.7B",
    "sha": "09a7ee948647508b82c29f1ce73dadcf2a73cbec",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-ExecuTorch",
    "name": "Qwen3-4B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B",
    "sha": "ee28bb1356e4a2b243a8d796988073238df35877",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-Instruct-2507-ExecuTorch",
    "name": "Qwen3-4B-Instruct-2507",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B-Instruct-2507",
    "sha": "3967479600e85fda68e48724a958091a481bb455",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-135M-Instruct-ExecuTorch",
    "name": "SmolLM2-135M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-135M-Instruct",
    "sha": "720399c83ad6ebabcd8e966165c41f6fe63e2c3d",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-360M-Instruct-ExecuTorch",
    "name": "SmolLM2-360M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-360M-Instruct",
    "sha": "90950924fa3ac339d0b18a6505a8633757943865",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "fp32 linears",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  }
];
