// GENERATED by scripts/build-execupack-data.mjs from the Hugging Face API
// (huggingface.co/experimentalmachines, every *-ExecuTorch repo). Do not edit by hand; re-run the script.
// One entry per published repo; builds group its .pte files by backend folder,
// chip and recipe, with the context windows (tokens) present.

export type PublishedBuild = {
  backend: "xnnpack" | "vulkan" | "qnn" | "mtk";
  chip: string | null;
  recipe: string;
  windows: number[];
};

export type PublishedRepo = {
  id: string;
  name: string;
  family: string;
  source: string | null;
  sha: string;
  lastModified: string;
  builds: PublishedBuild[];
};

export const publishedAsOf = "2026-09-24";

export const publishedRepos: PublishedRepo[] = [
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-1.2B-Instruct",
    "sha": "8184ae83cf4da8d5d337baa31197c6b85535dc3e",
    "lastModified": "2026-09-24",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic",
    "sha": "79c5f416ae78381df8ebf2ba46fe01e1a4313db4",
    "lastModified": "2026-09-22",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W4",
        "windows": [
          512
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-ExecuTorch",
    "name": "LFM2.5-2.6B",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-2.6B",
    "sha": "d661b4c17092530e7c31586360b318e84be69ed3",
    "lastModified": "2026-09-22",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W4",
        "windows": [
          512
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-heretic-ExecuTorch",
    "name": "LFM2.5-2.6B-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-2.6B-heretic",
    "sha": "be0315ac882d75d0612e5d2e5b39085da2c80707",
    "lastModified": "2026-09-22",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W4",
        "windows": [
          512
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-1B-Instruct-ExecuTorch",
    "name": "Llama-3.2-1B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-1B-Instruct",
    "sha": "09424c362ef82cb243e6dc97e51dc14a2d712ba9",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-3B-Instruct-ExecuTorch",
    "name": "Llama-3.2-3B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-3B-Instruct",
    "sha": "4b255a6d579c419dc04cc35757699a5f63306b8c",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-0.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-0.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-0.5B-Instruct",
    "sha": "a246424735666550c0446c1d5eaab26de142b783",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-1.5B-Instruct",
    "sha": "6c70ab32013377454d4248f73a22c86ee2491e14",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-3B-Instruct-ExecuTorch",
    "name": "Qwen2.5-3B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-3B-Instruct",
    "sha": "746d6ad9511ceca6733a5a9232a9d2ae9dbb85ce",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-Math-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-Math-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-Math-1.5B-Instruct",
    "sha": "83203a988f614aec0b531c839435debb41ebfb66",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-0.6B-ExecuTorch",
    "name": "Qwen3-0.6B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-0.6B",
    "sha": "909dd2dcbdabdd469625aa6d228c9f362e6764bd",
    "lastModified": "2026-09-18",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-1.7B-ExecuTorch",
    "name": "Qwen3-1.7B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-1.7B",
    "sha": "7fb16c28aa100f974c41d35463efe8c9a18a261f",
    "lastModified": "2026-09-20",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-ExecuTorch",
    "name": "Qwen3-4B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B",
    "sha": "3b74f69e91b8fd9f6cd74516b27d4511540a1618",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-Instruct-2507-ExecuTorch",
    "name": "Qwen3-4B-Instruct-2507",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B-Instruct-2507",
    "sha": "055bfc3ece6cb3b5196475ad511ecb5c71646d0d",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-135M-Instruct-ExecuTorch",
    "name": "SmolLM2-135M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-135M-Instruct",
    "sha": "4cd2b22cdc98aa6f9af45cba049ce6d35ecd16fd",
    "lastModified": "2026-09-18",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-360M-Instruct-ExecuTorch",
    "name": "SmolLM2-360M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-360M-Instruct",
    "sha": "4c5b78b5f9ff29a9529e2211066ac62ec6e4f845",
    "lastModified": "2026-09-13",
    "builds": [
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  }
];
