// GENERATED by scripts/build-execupack-data.mjs from the Hugging Face API
// (huggingface.co/experimentalmachines, every *-ExecuTorch repo). Do not edit by hand; re-run the script.
// One entry per published repo; builds group its .pte files by backend folder,
// chip and recipe, with the context windows (tokens) present.

export type PublishedBuild = {
  backend: "xnnpack" | "vulkan" | "qnn" | "mtk";
  chip: string | null;
  recipe: string;
  windows: number[];
};

export type PublishedRepo = {
  id: string;
  name: string;
  family: string;
  source: string | null;
  sha: string;
  lastModified: string;
  builds: PublishedBuild[];
};

export const publishedAsOf = "2026-10-08";

export const publishedRepos: PublishedRepo[] = [
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-1.2B-Instruct",
    "sha": "8184ae83cf4da8d5d337baa31197c6b85535dc3e",
    "lastModified": "2026-09-24",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic-ExecuTorch",
    "name": "LFM2.5-1.2B-Instruct-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-1.2B-Instruct-heretic",
    "sha": "e44b7567936ed69a3ce1052772876313df9b750e",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-ExecuTorch",
    "name": "LFM2.5-2.6B",
    "family": "lfm2",
    "source": "LiquidAI/LFM2.5-2.6B",
    "sha": "5e8cb9228aeee7ac35daf044b78e05a93ef7b65b",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/LFM2.5-2.6B-heretic-ExecuTorch",
    "name": "LFM2.5-2.6B-heretic",
    "family": "lfm2",
    "source": "experimentalmachines/LFM2.5-2.6B-heretic",
    "sha": "61a2a59affbb7f06bfdc9bd9644d0cc3e3b2d778",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          512,
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-1B-Instruct-ExecuTorch",
    "name": "Llama-3.2-1B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-1B-Instruct",
    "sha": "5d7f93d5ebedb13be93a840f31a1c629327484bf",
    "lastModified": "2026-10-07",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "qnn",
        "chip": "SM8750",
        "recipe": "QNN HTP",
        "windows": [
          2048,
          4096
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Llama-3.2-3B-Instruct-ExecuTorch",
    "name": "Llama-3.2-3B-Instruct",
    "family": "llama3_2",
    "source": "meta-llama/Llama-3.2-3B-Instruct",
    "sha": "95873ccbc231d67c42ea82e51efe253c6919b7e0",
    "lastModified": "2026-10-07",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "qnn",
        "chip": "SM8750",
        "recipe": "QNN HTP",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-0.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-0.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-0.5B-Instruct",
    "sha": "cff4d0471726bcb582f0d013a74ba36f26d86ff6",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-1.5B-Instruct",
    "sha": "0a912670f4bf6039d0192cc420960039bff0d402",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-3B-Instruct-ExecuTorch",
    "name": "Qwen2.5-3B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-3B-Instruct",
    "sha": "02ce1e421aaa50e64f895b77ec8ee6e6d678a515",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen2.5-Math-1.5B-Instruct-ExecuTorch",
    "name": "Qwen2.5-Math-1.5B-Instruct",
    "family": "qwen2_5",
    "source": "Qwen/Qwen2.5-Math-1.5B-Instruct",
    "sha": "aa5e6b9e4b4a41767dfbaeaac1dcd98b29560620",
    "lastModified": "2026-10-03",
    "builds": [
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-0.6B-ExecuTorch",
    "name": "Qwen3-0.6B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-0.6B",
    "sha": "07f9ba4bd321668eb901dc45b1bf55b452e242be",
    "lastModified": "2026-10-07",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          4096,
          8192
        ]
      },
      {
        "backend": "qnn",
        "chip": "SM8750",
        "recipe": "QNN HTP",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-1.7B-ExecuTorch",
    "name": "Qwen3-1.7B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-1.7B",
    "sha": "3c3b6cead7549147f390787ec05c5d509d397647",
    "lastModified": "2026-10-08",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "qnn",
        "chip": "SM8750",
        "recipe": "QNN HTP",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-ExecuTorch",
    "name": "Qwen3-4B",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B",
    "sha": "ee28bb1356e4a2b243a8d796988073238df35877",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/Qwen3-4B-Instruct-2507-ExecuTorch",
    "name": "Qwen3-4B-Instruct-2507",
    "family": "qwen3",
    "source": "Qwen/Qwen3-4B-Instruct-2507",
    "sha": "3967479600e85fda68e48724a958091a481bb455",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-135M-Instruct-ExecuTorch",
    "name": "SmolLM2-135M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-135M-Instruct",
    "sha": "c0d4461c7fffccf692266b1eae07b056091cb140",
    "lastModified": "2026-10-07",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "qnn",
        "chip": "SM8750",
        "recipe": "QNN HTP",
        "windows": [
          2048,
          4096,
          8192
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "8da4w GPTQ",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  },
  {
    "id": "experimentalmachines/SmolLM2-360M-Instruct-ExecuTorch",
    "name": "SmolLM2-360M-Instruct",
    "family": "smollm2",
    "source": "HuggingFaceTB/SmolLM2-360M-Instruct",
    "sha": "06e462dc6a7e930d4637738fba54512703c4f0ff",
    "lastModified": "2026-10-04",
    "builds": [
      {
        "backend": "mtk",
        "chip": "MT6991",
        "recipe": "A16W8",
        "windows": [
          2048,
          4096,
          8192,
          16384
        ]
      },
      {
        "backend": "vulkan",
        "chip": null,
        "recipe": "8da4w",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      },
      {
        "backend": "xnnpack",
        "chip": null,
        "recipe": "fp32 linears",
        "windows": [
          2048,
          4096,
          8192,
          16384,
          32768
        ]
      }
    ]
  }
];
