// GENERATED by scripts/build-gguf-bf16-data.mjs from github.com/arjhinety/OpenGrad at
// tag study-001 (results/quantization/gguf, results/benchmarks/h200). Do not edit by hand; re-run the script.
// Two runs of the same M1-v2 checkpoint, joined for comparison and NOT on the
// same hardware. llama.cpp ran the BF16 GGUF on one A100, single stream,
// llama-bench: tg = generation of 128 tokens, pp = prompt processing at 2,048
// tokens. vLLM ran the BF16 checkpoint on one H200, batching 1 to 256, three
// shapes plus a mixed one. Engine, GPU and kernels all differ, so this is an
// engine-level comparison and not a measurement of either engine or GPU alone.
// Decisions compares the two engines per example on the same 1,277 confirmatory
// prompts; the quantized-rung flip counts come from the A100 ladder and use the
// llama.cpp BF16 GGUF as their reference.

export const ggufBf16Links = {
  "report": "https://github.com/arjhinety/OpenGrad/blob/study-001/reports/H200_BENCHMARK_RUN.md",
  "results": "https://github.com/arjhinety/OpenGrad/tree/study-001/results/benchmarks/h200",
  "agreement": "https://github.com/arjhinety/OpenGrad/blob/study-001/results/benchmarks/h200/vllm_vs_llamacpp_agreement.json",
  "errata": "https://github.com/arjhinety/OpenGrad/blob/study-001/reports/ERRATA.md",
  "study": "https://opengrad.arjhinety.com/studies/001#quantization"
};

export const ggufBf16Conditions = {
  "llamacpp": {
    "artifact": "m1-v2-bf16.gguf",
    "bytes": 3775708704,
    "gib": 3.52,
    "tg": 251.1,
    "tgSd": 1.9,
    "pp": 21073,
    "ppSd": 23,
    "engine": "llama.cpp d3146f2, CUDA backend, llama-bench",
    "gpu": "NVIDIA A100-SXM4-80GB",
    "gpuShort": "A100",
    "offload": "all layers on the GPU",
    "batch": "2048 batch, 512 micro-batch, 24 CPU threads",
    "kvCache": "f16 keys, f16 values",
    "repetitions": 3,
    "runDate": "2026-09-12"
  },
  "vllm": {
    "engine": "vLLM 0.29.0, torch 2.13.0+cu130, CUDA 13.0",
    "gpu": "NVIDIA H200",
    "gpuShort": "H200",
    "driver": "580.95.05",
    "dtype": "bfloat16",
    "gpuMemoryGib": 139.8,
    "gpuHourlyUsd": 4.54,
    "maxModelLen": 5760,
    "maxNumSeqs": 256,
    "prefixCaching": false,
    "coldStartSeconds": 52.6,
    "billedUsdUpperBound": 0.11,
    "runDate": "2026-09-12"
  },
  "examples": 1277
};

export type ServingRow = {
  shape: string;
  concurrency: number;
  requestsPerSecond: number;
  outputTps: number;
  totalTps: number;
  promptTokens: number;
  outputTokens: number;
};

export const ggufBf16Sweep: ServingRow[] = [
  {
    "shape": "long",
    "concurrency": 1,
    "requestsPerSecond": 8.2,
    "outputTps": 139.1,
    "totalTps": 42977.4,
    "promptTokens": 5235,
    "outputTokens": 17
  },
  {
    "shape": "median",
    "concurrency": 1,
    "requestsPerSecond": 5.3,
    "outputTps": 270.5,
    "totalTps": 4455,
    "promptTokens": 789,
    "outputTokens": 51
  },
  {
    "shape": "mixed",
    "concurrency": 1,
    "requestsPerSecond": 8.5,
    "outputTps": 279.6,
    "totalTps": 406.6,
    "promptTokens": 15,
    "outputTokens": 33
  },
  {
    "shape": "short",
    "concurrency": 1,
    "requestsPerSecond": 6.8,
    "outputTps": 225.2,
    "totalTps": 327.5,
    "promptTokens": 15,
    "outputTokens": 33
  },
  {
    "shape": "mixed",
    "concurrency": 8,
    "requestsPerSecond": 41.7,
    "outputTps": 1158.5,
    "totalTps": 1826.5,
    "promptTokens": 128,
    "outputTokens": 222
  },
  {
    "shape": "mixed",
    "concurrency": 32,
    "requestsPerSecond": 118.2,
    "outputTps": 3323.5,
    "totalTps": 5901.1,
    "promptTokens": 698,
    "outputTokens": 900
  },
  {
    "shape": "mixed",
    "concurrency": 64,
    "requestsPerSecond": 208.4,
    "outputTps": 5814.6,
    "totalTps": 12042.6,
    "promptTokens": 1913,
    "outputTokens": 1786
  },
  {
    "shape": "mixed",
    "concurrency": 128,
    "requestsPerSecond": 269.6,
    "outputTps": 7794.3,
    "totalTps": 41523.7,
    "promptTokens": 16016,
    "outputTokens": 3701
  },
  {
    "shape": "mixed",
    "concurrency": 256,
    "requestsPerSecond": 259.9,
    "outputTps": 8312.7,
    "totalTps": 75138.1,
    "promptTokens": 65815,
    "outputTokens": 8187
  }
];

export const ggufBf16Mixed: ServingRow[] = [
  {
    "shape": "mixed",
    "concurrency": 1,
    "requestsPerSecond": 8.5,
    "outputTps": 279.6,
    "totalTps": 406.6,
    "promptTokens": 15,
    "outputTokens": 33
  },
  {
    "shape": "mixed",
    "concurrency": 8,
    "requestsPerSecond": 41.7,
    "outputTps": 1158.5,
    "totalTps": 1826.5,
    "promptTokens": 128,
    "outputTokens": 222
  },
  {
    "shape": "mixed",
    "concurrency": 32,
    "requestsPerSecond": 118.2,
    "outputTps": 3323.5,
    "totalTps": 5901.1,
    "promptTokens": 698,
    "outputTokens": 900
  },
  {
    "shape": "mixed",
    "concurrency": 64,
    "requestsPerSecond": 208.4,
    "outputTps": 5814.6,
    "totalTps": 12042.6,
    "promptTokens": 1913,
    "outputTokens": 1786
  },
  {
    "shape": "mixed",
    "concurrency": 128,
    "requestsPerSecond": 269.6,
    "outputTps": 7794.3,
    "totalTps": 41523.7,
    "promptTokens": 16016,
    "outputTokens": 3701
  },
  {
    "shape": "mixed",
    "concurrency": 256,
    "requestsPerSecond": 259.9,
    "outputTps": 8312.7,
    "totalTps": 75138.1,
    "promptTokens": 65815,
    "outputTokens": 8187
  }
];

export const ggufBf16Decisions = {
  "examples": 1277,
  "agreement": 0.9836,
  "flips": 21,
  "exactOutputAgreement": 0.87,
  "flipsTokenizerDivergent": 3,
  "flipsEngineNumerics": 18,
  "flipEffects": {
    "bothWrong": 2,
    "llamacppCorrect": 14,
    "vllmCorrect": 5
  },
  "note": "vLLM ran on H200 (BF16); llama.cpp ran the BF16 GGUF on A100. Engine, hardware and kernels all differ, so this is an engine-level comparison, not a quantization one."
};

export const ggufBf16QuantFlips = [
  {
    "rung": "Q8_0",
    "flips": 17,
    "agreement": 0.9867
  },
  {
    "rung": "Q6_K",
    "flips": 25,
    "agreement": 0.9804
  },
  {
    "rung": "Q5_K_M",
    "flips": 64,
    "agreement": 0.9499
  },
  {
    "rung": "IQ4_XS",
    "flips": 149,
    "agreement": 0.8833
  },
  {
    "rung": "Q4_K_S",
    "flips": 155,
    "agreement": 0.8786
  },
  {
    "rung": "Q4_K_M",
    "flips": 164,
    "agreement": 0.8716
  },
  {
    "rung": "Q3_K_M",
    "flips": 292,
    "agreement": 0.7713
  },
  {
    "rung": "IQ3_M",
    "flips": 292,
    "agreement": 0.7713
  },
  {
    "rung": "Q2_K",
    "flips": 595,
    "agreement": 0.5341
  }
];

export const ggufBf16Rerun = {
  "callF1": 0.7505,
  "referenceCallF1": 0.7548,
  "maxAbsDelta": 0.011,
  "parseValidRate": 1
};
