// GENERATED by scripts/build-gguf-data.mjs from github.com/arjhinety/OpenGrad at
// tag study-001 (results/quantization/gguf). Do not edit by hand; re-run the script.
// The M1-v2 checkpoint (Qwen3.5-2B, OpenGrad Study 001) as BF16 GGUF and nine
// imatrix quantizations. Throughput is llama-bench: pp = prompt processing at
// 2,048 tokens, tg = generation of 128 tokens, tokens per second, mean and
// standard deviation over the repetitions. Agreement is the share of the
// confirmatory examples where the format made the same tool-use decision as
// the BF16 GGUF.

export const ggufLinks = {
  "report": "https://github.com/arjhinety/OpenGrad/blob/study-001/reports/QUANTIZATION_PTQ_EVALUATION.md",
  "results": "https://github.com/arjhinety/OpenGrad/tree/study-001/results/quantization/gguf",
  "errata": "https://github.com/arjhinety/OpenGrad/blob/study-001/reports/ERRATA.md",
  "study": "https://opengrad.arjhinety.com/studies/001#quantization",
  "model": "https://huggingface.co/arrochi112/OpenGrad-Qwen3.5-2B-M1-DPO-CanonicalV2-Final-v2"
};

export const ggufConditions = {
  "pp512MaxRelSd": 0.282,
  "engine": "llama.cpp d3146f2, CUDA backend, llama-bench",
  "gpu": "NVIDIA A100-SXM4-80GB",
  "params": 1881825088,
  "offload": "all layers on the GPU",
  "batch": "2048 batch, 512 micro-batch, 24 CPU threads",
  "kvCache": "f16 keys, f16 values",
  "repetitions": 3,
  "runDate": "2026-09-12",
  "examples": 1277
};

export const ggufRecommended = "Q6_K";

export type GgufRow = {
  format: string;
  bytes: number;
  gib: number;
  bitsPerWeight: number;
  tg: number;
  tgSd: number;
  pp: number;
  ppSd: number;
  agreement: number | null;
  passes: boolean;
};

export const ggufRows: GgufRow[] = [
  {
    "format": "BF16",
    "bytes": 3775708704,
    "gib": 3.52,
    "bitsPerWeight": 16.05,
    "tg": 251.1,
    "tgSd": 1.9,
    "pp": 21073,
    "ppSd": 23,
    "agreement": null,
    "passes": true
  },
  {
    "format": "Q2_K",
    "bytes": 968541952,
    "gib": 0.9,
    "bitsPerWeight": 4.12,
    "tg": 284.8,
    "tgSd": 3.6,
    "pp": 9623,
    "ppSd": 6,
    "agreement": 0.5341,
    "passes": false
  },
  {
    "format": "Q3_K_M",
    "bytes": 1099258624,
    "gib": 1.02,
    "bitsPerWeight": 4.67,
    "tg": 268.8,
    "tgSd": 3.6,
    "pp": 10879,
    "ppSd": 12,
    "agreement": 0.7713,
    "passes": false
  },
  {
    "format": "IQ3_M",
    "bytes": 1059445504,
    "gib": 0.99,
    "bitsPerWeight": 4.5,
    "tg": 283.4,
    "tgSd": 3.1,
    "pp": 12420,
    "ppSd": 27,
    "agreement": 0.7713,
    "passes": false
  },
  {
    "format": "IQ4_XS",
    "bytes": 1195962112,
    "gib": 1.11,
    "bitsPerWeight": 5.08,
    "tg": 306.3,
    "tgSd": 3.5,
    "pp": 13288,
    "ppSd": 20,
    "agreement": 0.8833,
    "passes": false
  },
  {
    "format": "Q4_K_S",
    "bytes": 1212055296,
    "gib": 1.13,
    "bitsPerWeight": 5.15,
    "tg": 299.2,
    "tgSd": 5.6,
    "pp": 12436,
    "ppSd": 40,
    "agreement": 0.8786,
    "passes": false
  },
  {
    "format": "Q4_K_M",
    "bytes": 1274396416,
    "gib": 1.19,
    "bitsPerWeight": 5.42,
    "tg": 292.7,
    "tgSd": 3.2,
    "pp": 12200,
    "ppSd": 9,
    "agreement": 0.8716,
    "passes": false
  },
  {
    "format": "Q5_K_M",
    "bytes": 1411120896,
    "gib": 1.31,
    "bitsPerWeight": 6,
    "tg": 292.9,
    "tgSd": 1.7,
    "pp": 12414,
    "ppSd": 20,
    "agreement": 0.9499,
    "passes": false
  },
  {
    "format": "Q6_K",
    "bytes": 1556390656,
    "gib": 1.45,
    "bitsPerWeight": 6.62,
    "tg": 267.7,
    "tgSd": 2.8,
    "pp": 11914,
    "ppSd": 18,
    "agreement": 0.9804,
    "passes": true
  },
  {
    "format": "Q8_0",
    "bytes": 2012012288,
    "gib": 1.87,
    "bitsPerWeight": 8.55,
    "tg": 273.8,
    "tgSd": 1.8,
    "pp": 13297,
    "ppSd": 22,
    "agreement": 0.9867,
    "passes": true
  }
];
